import 'package:get/get.dart';

class Language extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {

    'en_US' : {
      'lang'    : 'Language :',
      'setPage' : 'Settings',
      'blockQuote'   : 'Quote [CLick to expand]: ',
      'notification'    : 'Alerts',
      'inbox'   : 'Inbox',
      'rep'     : 'Reply',
      'loading' : 'Loading',
      'loading3': 'Loading...',
      'pullUp'  : 'Pull Up To Next Page',
      'pullRes' : 'Release To Load',
      'popMess' : 'Hang tight',
      'popMess2' : 'I\'m processing your request',
      'popMess3' : 'I\'m refreshing',
      'popMess4' : 'You must loggin to react',
      'popMess5' : 'I\'m posting your react',
      'status' : 'Status',
      'statusLoginFail' : "Incorrect ID/Password or server busy\nIf this continue happens, please restart app and try again",
      'statusLoginInvalid' : 'Login or Password maybe too short ?',
      'statusLoginOK' : 'Success',
      'loginMess' : 'Log in your account',
      'loginAccount' : 'Account',
      'loginPassword' : 'Password',
      'login'   : 'Login',
      'logout'  : 'Logout',
      'error'   : 'Error',
      'fontSizeView' : 'Font size :',
      'unReact' : 'UnReact',
      'react' : 'React ?',
      'sweet' : 'Sweet',
      'brick' : 'Brick',
      'sweeted' : 'Sweet',
      'bricked' : 'Brick',
      'createPost' : 'New Post',
      'editPost' : 'Edit Post',
      'newConversation' : 'Start conversation',
      'newThread' : 'Post thread',
      'scrollToMyRepAfterPost' : 'Enable Scroll To My Post:',
      'showImage' : 'Display Image',
      'appSignature' : 'App Signature',
    },
    'vi_VN' : {
      'lang'    : 'Ngôn ngữ :',
      'setPage' : 'Cài Đặt',
      'blockQuote'   : 'Quote [Bấm để xem]: ',
      'notification'    : 'Thông Báo',
      'inbox'   : 'Hộp Thư',
      'rep'     : 'Trả lời',
      'loading' : 'Đang láy dữ liệu',
      'loading3': 'Đang láy dữ liệu...',
      'pullUp'  : 'Kéo lên để chuyển trang',
      'pullRes' : 'Thả ra để load',
      'popMess' : 'Đợi một tí',
      'popMess2' : 'Đang xứ lí yêu cầu của bạn',
      'popMess3' : 'Đang cập nhật thông tin người dùng',
      'popMess4' : 'Bạn phả đăng nhập để react',
      'popMess5' : 'Đang xử lí React',
      'status'  : 'Trang Thái',
      'statusLoginFail' : 'Sai tài khoản/mât khảu hoạc không thể kêt nối tới server/api\nNếu bạn vẩn không đăng nhâp được, hãy thử thoát app và chạy lại',
      'statusLoginInvalid' : 'Tài khoản hoạc mật khẩu quá ngắn hoặc không hợp lệ',
      'statusLoginOK' : 'Đăng nhập thành công',
      'loginMess' : 'Hãy Đăng Nhập Vào Tài Khoản Của bạn',
      'loginAccount' : 'Tài Khoản',
      'loginPassword' : 'Mật Khẩu',
      'login'   : 'Đăng Nhập',
      'logout'  : 'Đăng Xuất',
      'error'   : 'Thông Báo Lỗi',
      'fontSizeView' : 'Kích Cỡ Chữ :',
      'unReact' : 'Bỏ React',
      'react' : 'Ưng ?',
      'sweet' : 'Ưng',
      'brick' : 'Gạch',
      'sweeted' : 'Đả Ưng',
      'bricked' : 'Đả Gạch',
      'createPost' : 'Bài Viet Mới',
      'editPost' : 'Chỉnh sửa Post',
      'newConversation' : 'Start conversation',
      'newThread' : 'Post thread',
      'scrollToMyRepAfterPost' : 'Tự Động Đến Trang Vừa Trả Lời :',
      'showImage' : 'Hiển Thị Hình Ảnh:',
      'appSignature' : 'Chữ Ký Ứng Dụng',
    }
  };

}