final List smallVozEmoji = [
  {'dir': "popo/smile.png", 'symbol': ':)'},
  {'dir': "popo/wink.png", 'symbol': ";)"},
  {'dir': "popo/frown.png", 'symbol': ":("},
  {'dir': "popo/mad.png", 'symbol': ":mad:"},
  {'dir': "popo/confused.png", 'symbol': ":confused:"},
  {'dir': "popo/cool.png", 'symbol': "8-)"},
  {'dir': "popo/tongue.png", 'symbol': ":p"},
  {'dir': "popo/biggrin.png", 'symbol': ":D"},
  {'dir': "popo/eek.png", 'symbol': ":eek:"},
  {'dir': "popo/redface.png", 'symbol': ":oops:"},
  {'dir': "popo/rolleyes.png", 'symbol': ":rolleyes:"},
  {'dir': "popo/O_o.png", 'symbol': "o_O"},
  {'dir': "popo/cautious.png", 'symbol': ":cautious:"},
  {'dir': "popo/speechless.png", 'symbol': ":censored:"},
  {'dir': "popo/cry.png", 'symbol': "=(("},
  {'dir': "popo/inlove.png", 'symbol': ":love:"},
  {'dir': "popo/laugh.png", 'symbol': ":LOL:"},
  {'dir': "popo/roflmao.png", 'symbol': ":ROFLMAO:"},
  {'dir': "popo/sick.png", 'symbol': ":sick:"},
  {'dir': "popo/sleep.png", 'symbol': ":sleep:"},
  {'dir': "popo/sneaky.png", 'symbol': ":sneaky:"},
  {'dir': "popo/unsure.png", 'symbol': ":unsure:"},
  {'dir': "popo/whistling.png", 'symbol': ":whistle:"},
  {'dir': "popo/giggle.png", 'symbol': ":giggle:"},
  {'dir': "popo/devilish.png", 'symbol': ":devilish:"}
];

final List bigVozEmoji = [
  {'dir': "popopo/adore.png", 'symbol': ":adore:"},
  {'dir': "popopo/after_boom.png", 'symbol': ":after_boom:"},
  {'dir': "popopo/ah.png", 'symbol': ":ah:"},
  {'dir': "popopo/amazed.png", 'symbol': ":amazed:"},
  {'dir': "popopo/angry.png", 'symbol': ":angry:"},
  {'dir': "popopo/bad_smelly.png", 'symbol': ":bad_smelly:"},
  {'dir': "popopo/baffle.png", 'symbol': ":baffle:"},
  {'dir': "popopo/beat_brick.png", 'symbol': ":beat_brick:"},
  {'dir': "popopo/beat_plaster.png", 'symbol': ":beat_plaster:"},
  {'dir': "popopo/beat_shot.png", 'symbol': ":beat_shot:"},
  {'dir': "popopo/beated.png", 'symbol': ":beated:"},
  {'dir': "popopo/beauty.png", 'symbol': ":beauty:"},
  {'dir': "popopo/big_smile.png", 'symbol': ":big_smile:"},
  {'dir': "popopo/boss.png", 'symbol': ":boss:"},
  {'dir': "popopo/burn_joss_stick.png", 'symbol': ":burn_joss_stick:"},
  {'dir': "popopo/byebye.png", 'symbol': ":byebye:"},
  {'dir': "popopo/canny.png", 'symbol': ":canny:"},
  {'dir': "popopo/choler.png", 'symbol': ":choler:"},
  {'dir': "popopo/cold.png", 'symbol': ":cold:"},
  {'dir': "popopo/confident.png", 'symbol': ":confident:"},
  {'dir': "popopo/confuse.png", 'symbol': ":confuse:"},
  {'dir': "popopo/cool.png", 'symbol': ":cool:"},
  {'dir': "popopo/cry.png", 'symbol': ":cry:"},
  {'dir': "popopo/doubt.png", 'symbol': ":doubt:"},
  {'dir': "popopo/dribble.png", 'symbol': ":dribble:"},
  {'dir': "popopo/embarrassed.png", 'symbol': ":embarrassed:"},
  {'dir': "popopo/extreme_sexy_girl.png", 'symbol': ":extreme_sexy_girl:"},
  {'dir': "popopo/feel_good.png", 'symbol': ":feel_good:"},
  {'dir': "popopo/go.png", 'symbol': ":go:"},
  {'dir': "popopo/haha.png", 'symbol': ":haha:"},
  {'dir': "popopo/hell_boy.png", 'symbol': ":hell_boy:"},
  {'dir': "popopo/hungry.png", 'symbol': ":hungry:"},
  {'dir': "popopo/look_down.png", 'symbol': ":look_down:"},
  {'dir': "popopo/matrix.png", 'symbol': ":matrix:"},
  {'dir': "popopo/misdoubt.png", 'symbol': ":misdoubt:"},
  {'dir': "popopo/nosebleed.png", 'symbol': ":nosebleed:"},
  {'dir': "popopo/oh.png", 'symbol': ":oh:"},
  {'dir': "popopo/ops.png", 'symbol': ":ops:"},
  {'dir': "popopo/pudency.png", 'symbol': ":pudency:"},
  {'dir': "popopo/rap.png", 'symbol': ":rap:"},
  {'dir': "popopo/sad.png", 'symbol': "sad:"},
  {'dir': "popopo/sexy_girl.png", 'symbol': ":sexy_girl:"},
  {'dir': "popopo/shame.png", 'symbol': ":shame:"},
  {'dir': "popopo/smile.png", 'symbol': ":smile:"},
  {'dir': "popopo/spiderman.png", 'symbol': ":spiderman:"},
  {'dir': "popopo/still_dreaming.png", 'symbol': ":still_dreaming:"},
  {'dir': "popopo/sure.png", 'symbol': ":sure:"},
  {'dir': "popopo/surrender.png", 'symbol': ":surrender:"},
  {'dir': "popopo/sweat.png", 'symbol': ":sweat:"},
  {'dir': "popopo/sweet_kiss.png", 'symbol': ":sweet_kiss:"},
  {'dir': "popopo/tire.png", 'symbol': ":tire:"},
  {'dir': "popopo/too_sad.png", 'symbol': ":too_sad:"},
  {'dir': "popopo/waaaht.png", 'symbol': ":waaaht:"},
  {'dir': "popopo/what.png", 'symbol': ":what:"}
];

// https://raw.githubusercontent.com/haophan69/Pepe/main/Pepe4.webp
final List mapEmojiVozGif = [
  {'dir': '', 'symbol': ''},
];

final Map<String, String> mapEmojiVoz = {
  "popo/smile.png": ':)',
  "popo/wink.png": ";)",
  "popo/frown.png": ":(",
  "popo/mad.png": ":mad:",
  "popo/confused.png": ":confused:",
  "popo/cool.png": "8-)",
  "popo/tongue.png": ":p",
  "popo/biggrin.png": ":D",
  "popo/eek.png": ":eek:",
  "popo/redface.png": ":oops:",
  "popo/rolleyes.png": ":rolleyes:",
  "popo/O_o.png": "o_O",
  "popo/cautious.png": ":cautious:",
  "popo/speechless.png": ":censored:",
  "popo/cry.png": "=((",
  "popo/inlove.png": ":love:",
  "popo/laugh.png": ":LOL:",
  "popo/roflmao.png": ":ROFLMAO:",
  "popo/sick.png": ":sick:",
  "popo/sleep.png": ":sleep:",
  "popo/sneaky.png": ":sneaky:",
  "popo/unsure.png": ":unsure:",
  "popo/whistling.png": ":whistle:",
  "popo/giggle.png": ":giggle:",
  "popo/devilish.png": ":devilish:",
  "popopo/adore.png": ":adore:",
  "popopo/after_boom.png": ":after_boom:",
  "popopo/ah.png": ":ah:",
  "popopo/amazed.png": ":amazed:",
  "popopo/angry.png": ":angry:",
  "popopo/bad_smelly.png": ":bad_smelly:",
  "popopo/baffle.png": ":baffle:",
  "popopo/beat_brick.png": ":beat_brick:",
  "popopo/beat_plaster.png": ":beat_plaster:",
  "popopo/beat_shot.png": ":beat_shot:",
  "popopo/beated.png": ":beated:",
  "popopo/beauty.png": ":beauty:",
  "popopo/big_smile.png": ":big_smile:",
  "popopo/boss.png": ":boss:",
  "popopo/burn_joss_stick.png": ":burn_joss_stick:",
  "popopo/byebye.png": ":byebye:",
  "popopo/canny.png": ":canny:",
  "popopo/choler.png": ":choler:",
  "popopo/cold.png": ":cold:",
  "popopo/confident.png": ":confident:",
  "popopo/confuse.png": ":confuse:",
  "popopo/cool.png": ":cool:",
  "popopo/cry.png": ":cry:",
  "popopo/doubt.png": ":doubt:",
  "popopo/dribble.png": ":dribble:",
  "popopo/embarrassed.png": ":embarrassed:",
  "popopo/extreme_sexy_girl.png": ":extreme_sexy_girl:",
  "popopo/feel_good.png": ":feel_good:",
  "popopo/go.png": ":go:",
  "popopo/haha.png": ":haha:",
  "popopo/hell_boy.png": ":hell_boy:",
  "popopo/hungry.png": ":hungry:",
  "popopo/look_down.png": ":look_down:",
  "popopo/matrix.png": ":matrix:",
  "popopo/misdoubt.png": ":misdoubt:",
  "popopo/nosebleed.png": ":nosebleed:",
  "popopo/oh.png": ":oh:",
  "popopo/ops.png": ":ops:",
  "popopo/pudency.png": ":pudency:",
  "popopo/rap.png": ":rap:",
  "popopo/sad.png": "sad:",
  "popopo/sexy_girl.png": ":sexy_girl:",
  "popopo/shame.png": ":shame:",
  "popopo/smile.png": ":smile:",
  "popopo/spiderman.png": ":spiderman:",
  "popopo/still_dreaming.png": ":still_dreaming:",
  "popopo/sure.png": ":sure:",
  "popopo/surrender.png": ":surrender:",
  "popopo/sweat.png": ":sweat:",
  "popopo/sweet_kiss.png": ":sweet_kiss:",
  "popopo/tire.png": ":tire:",
  "popopo/too_sad.png": ":too_sad:",
  "popopo/waaaht.png": ":waaaht:",
  "popopo/what.png": ":what:",
};