import 'package:get/get.dart';

class Language extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {

    'en_US' : {
      'lang'    : 'Language :',
      'setPage' : 'Settings',
      'blockQuote'   : 'Quote [CLick to expand]: ',
      'notification'    : 'Alerts',
      'inbox'   : 'Inbox',
      'rep'     : 'Reply',
      'pullUp'  : 'Pull Up To Next Page',
      'pullRes' : 'Release To Load',
      'status' : 'Status',
      'statusLoginFail' : "Incorrect ID/Password or server busy\nIf this continue happens, please restart app and try again",
      'statusLoginInvalid' : 'ID/Password too short',
      'statusLoginOK' : 'Success',
      'loginAccount' : 'Your name or email address',
      'show' : 'Show',
      'hide' : 'Hide',
      'or' : '\tor\t',
      'loginPassword' : 'Password',
      'login'   : 'Log in',
      'logout'  : 'Logout',
      'forgotPass' : 'Forgot your password?',
      'error'   : 'Error',
      'fontSizeView' : 'Font size :',
      'unReact' : 'UnReact',
      'react' : 'React ?',
      'sweet' : 'Sweet',
      'brick' : 'Brick',
      'sweeted' : 'Sweet',
      'bricked' : 'Brick',
      'createPost' : 'New Post',
      'editPost' : 'Edit Post',
      'newConversation' : 'Start conversation',
      'newThread' : 'Post thread',
      'scrollToMyRepAfterPost' : 'Enable Scroll To My Post:',
      'showImage' : 'Display Image',
      'appSignature' : 'App Signature',
      'defaultsPage' : 'Default Forum',
    },
    'vi_VN' : {
      'lang'    : 'Ngôn ngữ :',
      'setPage' : 'Cài Đặt',
      'blockQuote'   : 'Quote [Bấm để xem]: ',
      'notification'    : 'Thông Báo',
      'inbox'   : 'Hộp Thư',
      'rep'     : 'Trả lời',
      'pullUp'  : 'Kéo lên để chuyển trang',
      'pullRes' : 'Thả ra để load',
      'status'  : 'Trang Thái',
      'statusLoginFail' : 'Sai tài khoản/mât khảu hoạc không thể kêt nối tới server/api\nNếu bạn vẩn không đăng nhâp được, hãy thử thoát app và chạy lại',
      'statusLoginInvalid' : 'Tài khoản/mật khẩu quá ngắn',
      'statusLoginOK' : 'Đăng nhập thành công',
      'show' : 'Ẩn',
      'hide' : 'Hiện',
      'or' : '\thoặc\t',
      'loginAccount' : 'Tên hoặc email của bạn',
      'loginPassword' : 'Mật Khẩu',
      'login'   : 'Đăng Nhập',
      'forgotPass' : 'Quên mật khẩu?',
      'logout'  : 'Đăng Xuất',
      'error'   : 'Thông Báo Lỗi',
      'fontSizeView' : 'Kích Cỡ Chữ :',
      'unReact' : 'Bỏ React',
      'react' : 'Ưng ?',
      'sweet' : 'Ưng',
      'brick' : 'Gạch',
      'sweeted' : 'Đả Ưng',
      'bricked' : 'Đả Gạch',
      'createPost' : 'Bài Viet Mới',
      'editPost' : 'Chỉnh sửa Post',
      'newConversation' : 'Start conversation',
      'newThread' : 'Post thread',
      'scrollToMyRepAfterPost' : 'Tự Động Đến Trang Vừa Trả Lời :',
      'showImage' : 'Hiển Thị Hình Ảnh:',
      'appSignature' : 'Chữ Ký Ứng Dụng',
      'defaultsPage' : 'Mặc Định Forum',
    }
  };

}