import 'package:get/get.dart';

class Language extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {

    'en_US' : {
      'lang'    : 'Language',
      'setPage' : 'Settings',
      'blockQuote'   : 'Quote [CLick to expand]: ',
      'notification'    : 'Alerts',
      'inbox'   : 'Inbox',
      'rep'     : 'Reply',
      'pullUp'  : 'Pull Up To Next Page',
      'pullRes' : 'Release To Load',
      'loading' : 'Loading...',
      'status' : 'Status',
      'statusLoginFail' : "Incorrect ID/Password or server busy\nIf this continue happens, please restart app and try again",
      'statusLoginInvalid' : 'ID/Password too short',
      'statusLoginOK' : 'Success',
      'loginAccount' : 'Your name or email address',
      'show' : 'Show',
      'hide' : 'Hide',
      'or' : '\tor\t',
      'loginPassword' : 'Password',
      'login'   : 'Log in',
      'forgotPass' : 'Forgot your password?',
      'error'   : 'Error',
      'fontSizeView' : 'Font size',
      'unReact' : 'UnReact',
      'react' : 'React ?',
      'sweet' : 'Sweet',
      'brick' : 'Brick',
      'sweeted' : 'Sweet',
      'bricked' : 'Brick',
      'createPost' : 'New Post',
      'editPost' : 'Edit Post',
      'newConversation' : 'Start conversation',
      'newThread' : 'Post thread',
      'scrollToMyRepAfterPost' : 'Enable Scroll To My Post',
      'showImage' : 'Display Image',
      'appSignature' : 'App Signature',
      'defaultsPage' : 'Default Forum',
      'search' : 'Search',
      'guestUser' : 'Guest user',
      'posts' : 'Posts',
      '/latest-activity' : 'Latest activity',
      '/whats-new/latest-activity' : 'Latest activity',
      '/whats-new/news-feed' : 'New Feed',
      'controlCenter' : ' Control Center',
      'latest' : 'Latest',
      'input' : 'Input',
      'please' : 'Please',
      'title' : 'Title',
      'recipients' : 'Recipients',
      'viewSwipeLeftRight' : 'Swipe Left/Right to Next',
      'keywords' : 'Keywords',
      'searchTitleOnly' : 'Search titles only',
      'postBy' : 'Posted by',
      'searchThreads' : 'Search threads (Optional)',
      'searchProfile' : 'Search profile posts',
      'follow' : 'Following | theNEXTvoz',
      'ignore' : 'Ignoring | theNEXTvoz',
      'shortcuts' : 'Shortcuts',
      'shortcutsHelper' : 'Long press on thread to save link',
      'darkMode' : 'Dark Mode',
      'iconBottomBarSize' : 'Icon Bottom Size',
      'heightBottom' : 'Height Bottom Bar',
    },
    'vi_VN' : {
      'lang'    : 'Ngôn Ngữ',
      'setPage' : 'Cài Đặt',
      'blockQuote'   : 'Quote [Bấm để xem]: ',
      'notification'    : 'Thông Báo',
      'inbox'   : 'Hộp Thư',
      'rep'     : 'Trả lời',
      'pullUp'  : 'Kéo lên để chuyển trang',
      'pullRes' : 'Thả ra để load',
      'loading' : 'Đang load ...',
      'status'  : 'Trang Thái',
      'statusLoginFail' : 'Sai tài khoản/mât khảu hoạc không thể kêt nối tới server/api\nNếu bạn vẩn không đăng nhâp được, hãy thử thoát app và chạy lại',
      'statusLoginInvalid' : 'Tài khoản/mật khẩu quá ngắn',
      'statusLoginOK' : 'Đăng nhập thành công',
      'show' : 'Ẩn',
      'hide' : 'Hiện',
      'or' : '\thoặc\t',
      'loginAccount' : 'Tên hoặc email của bạn',
      'loginPassword' : 'Mật Khẩu',
      'login'   : 'Đăng Nhập',
      'forgotPass' : 'Quên mật khẩu?',
      'error'   : 'Thông Báo Lỗi',
      'fontSizeView' : 'Kích Cỡ Chữ',
      'unReact' : 'Bỏ React',
      'react' : 'Ưng ?',
      'sweet' : 'Ưng',
      'brick' : 'Gạch',
      'sweeted' : 'Đã Ưng',
      'bricked' : 'Đã Gạch',
      'createPost' : 'Bài Viet Mới',
      'editPost' : 'Chỉnh sửa Post',
      'newConversation' : 'Start conversation',
      'newThread' : 'Post thread',
      'scrollToMyRepAfterPost' : 'Tự Động Đến Trang Vừa Trả Lời',
      'showImage' : 'Hiển Thị Hình Ảnh',
      'appSignature' : 'Chữ Ký Ứng Dụng',
      'defaultsPage' : 'Mặc Định Forum',
      'search' : 'Tìm Kiếm',
      'guestUser' : 'Khách',
      'posts' : 'Bản tin mới',
      '/latest-activity' : 'Hoạt động mới nhất',
      '/whats-new/latest-activity' : 'Hoạt động mới nhất',
      '/whats-new/news-feed' : 'Bảng Tin',
      'controlCenter' : 'Trung Tâm Điều Khiển',
      'latest' : 'Mới Nhất',
      'input' : 'Nhập',
      'title' : 'Tiêu Đề',
      'please' : 'Vui Lòng',
      'recipients' : 'Người Nhận',
      'viewSwipeLeftRight' : 'Vuốt Trái/Phải',
      'keywords' : 'Từ Khóa',
      'searchTitleOnly' : 'Chỉ tìm kiếm tiêu đề',
      'postBy' : 'Được đăng bởi',
      'searchThreads' : 'Tìm kiếm thớt (Optional)',
      'searchProfile' : 'Tìm kiếm profile posts',
      'follow' : 'Đang Theo Dõi | theNEXTvoz',
      'ignore' : 'Đang Chặn | theNEXTvoz',
      'shortcuts' : 'Đường dẫn nhanh',
      'shortcutsHelper' : 'Nhấn và giữ vào thớt để lưu đường dẫn',
      'darkMode' : 'Chế Độ Nền Tối',
      'iconBottomBarSize' : 'Kích Cỡ Icon Bottom',
      'heightBottom' : 'Kích cỡ Bottom Bar',
    }
  };

}